### ISSUE TITLE
Running in the browser

### ISSUE THREAD

**Issue by devTristan** [joshmarinacci/node-pureimage#1]
I'd really like to be able to run this in a web worker thread, operating on an [ImageData](https://developer.mozilla.org/en-US/docs/Web/API/ImageData).data, a [Uint8ClampedArray](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray). Is that possible?

I'd love to fork this and try to adapt it for the browser, but I'm not exactly sure if it's possible, or where to start.

**Comment by joshmarinacci** [comment]
I think it would be possible.  Currently it uses a Node Buffer internally to store the data. You could add another constructor to build a Bitmap4BBP object using a Uint8ClampedArray instead. The rest of the code should pretty much work as is.    Feel free to fork it and play around.

What is your use case?

**Comment by devTristan** [comment]
Hmm, okay, that makes sense.

My use case is that I want to do a lot of drawing off-screen and I don't want it to interfere with the UI thread. It's pretty quick (with native canvas) but even if it took a few hundred milliseconds w/ software rendering that'd be fine if it happened in a web worker. Basically trying to see if I can parallelize my drawing without having to write my own implementations of fill and stroke.
