### ISSUE TITLE
fillStyle = 'transparent' results in an exception of "unknown style format"

### ISSUE THREAD

**Issue by adedomin** [joshmarinacci/node-pureimage#106]
### Expected Behaviour

1. fillStyle = 'transparent' will set it to 0 and not throw

### Actual Behaviour

1. transparent style throws "unknown style format: transparent"

### Steps To Reproduce

1. ctx.fillStyle = 'transparent';

### Any Relevant Code Snippets

N/A, see Additional Info

### Platform
**OS:** Linux (Fedora 32)
**Node Version:** v12.16.3
**PureImage Version:** 0.2.1

### Any Additional Info

https://github.com/joshmarinacci/node-pureimage/blob/e67821f94422497dfca049dcee2a8aac8e820164/src/context.js#L1155

https://github.com/joshmarinacci/node-pureimage/blob/e67821f94422497dfca049dcee2a8aac8e820164/src/named_colors.js#L11

I believe the problem is "transparent" maps to 0 which is why the branch in context is always false for a set property of transparent.

**Comment by joshmarinacci** [comment]
arg. You're right. I'll add a test and fix it.

**Comment by joshmarinacci** [comment]
fixed now.
