### ISSUE TITLE
3-digit hex values are parsed incorrectly for fillStyle

### ISSUE THREAD

**Issue by adedomin** [joshmarinacci/node-pureimage#107]
### Expected Behaviour

1. ctx.fillStyle = '#999'; // should be a grey color
															
![Expected-Picture](https://user-images.githubusercontent.com/6037590/89105989-0fdf6100-d3f4-11ea-8608-2701099ac7c3.png)

### Actual Behaviour

1. ctx.fillStyle = '#999'; // is actually blue-ish

![Actual-Picture](https://user-images.githubusercontent.com/6037590/89105987-081fbc80-d3f4-11ea-9575-c7c85dc67838.png)

### Steps To Reproduce

1. See example snippet, or set ctx.fillStyle to any 3-digit hex value

### Any Relevant Code Snippets

```js
#!/usr/bin/env node
'use strict';

const PImage = require('pureimage');
const fs = require('fs');

const canvas = PImage.make(50,50);
const ctx = canvas.getContext('2d');

ctx.fillStyle = '#999';
// ctx.fillStyle = '#999999';
ctx.fillRect(0,0,50,50);

PImage.encodePNGToStream(
    ctx.bitmap,
    fs.createWriteStream('./example.png')
).then(() => console.log('xdg-open ./example.png'));
```

### Platform
**OS:** Linux Fedora 32
**Node Version:** v12
**NPM Version:** N/A
**PureImage Version:** 0.2.4

### Any Additional Info

Already fixed it. Wasn't sure if you want a PR for it or if you want to implement the fix yourself. Let me know. Side note, would you want all the defined CSS colors to be in named_colors? I can add them and I have an interest in them being included.

https://github.com/adedomin/node-pureimage/commit/699cf606f6ba002413fedd3446682358ae319de0#

**Comment by joshmarinacci** [comment]
I would love a PR. Thanks!

**Comment by Smiley43210** [comment]
Submitted PR #108 for this

**Comment by joshmarinacci** [comment]
merged.
