### ISSUE TITLE
setFillStyleRGBA not found

### ISSUE THREAD

**Issue by MMayla** [joshmarinacci/node-pureimage#11]
I tried this from the Readme
```
var img1 = PImage.make(100,50);
var ctx = img1.getContext('2d');
ctx.setFillStyleRGBA(255,0,0, 0.5);
```

But I get this error `TypeError: ctx.setFillStyleRGBA is not a function`

I have pureimage v0.0.13 and Nodejs v7.4.0

**Comment by upupzealot** [comment]
same problem

**Comment by joshmarinacci** [comment]
This was a combination of a missing feature and a bug in the docs. I've pushed out a new version which fixes it.  You should use ctx.fillStyle = 'rgba(255,0,0,0.5)', just like in webbrowsers.
