### ISSUE TITLE
Why pureImage name, there is already a framework with that name

### ISSUE THREAD

**Issue by memoryleakno1** [joshmarinacci/node-pureimage#12]
Not that it matters much, probably nobody cares, but just as info, there is already one framework with that name, and it's in your favourite language C++:

https://www.flll.jku.at/projects/pureImage

Seems dead by now ... anyway :-)

**Comment by joshmarinacci** [comment]
I had never heard of that one. This project is called pure image because it is a pure javascript implementation of image generation and manipulation.
