### ISSUE TITLE
Problem reading and/or writing png image to stream

### ISSUE THREAD

**Issue by taraxos** [joshmarinacci/node-pureimage#121]
My apologies if this is the wrong place to post this, but I couldn't find a more appropriate forum. I'm currently modifying an avatar generation script, and one of the steps involves using drawImage to draw images from png sources onto the canvas.

### Expected Behaviour

1. Image from png source should be drawn on canvas background

### Actual Behaviour

1. The avatar is saved as a png with the correct background but without the image from the png source

### Steps To Reproduce

1.

### Any Relevant Code Snippets

```ts
/**
 * Random avatar generator
 */

import * as p from 'pureimage';
import * as gen from 'random-seed';
import * as fs from 'fs';
import { WriteStream } from 'fs';
import { fileURLToPath } from 'url';
import { dirname } from 'path';
import { PassThrough } from 'stream';

//const _filename = fileURLToPath(import.meta.url);
const _filename = __filename;
const _dirname = dirname(_filename);

const passThroughStream = new PassThrough();

const size = 256; // px
const colors = [
	'#e57373',
	'#f06292',
	'#795548',
	'#455a64'
];

/**
 * Generate buffer of random avatar by seed
 */
export function genAvatar(seed: string, stream: WriteStream): Promise<void> {
	const rand = gen.create(seed);
	const canvas = p.make(size, size);
	const ctx = canvas.getContext('2d');

	ctx.fillStyle = colors[rand(colors.length)];
	ctx.beginPath();
	ctx.fillRect(0, 0, size, size);

	p.decodePNGFromStream(fs.createReadStream(`${_dirname}/img.png`)).then((img) => {
		ctx.drawImage(img, 0, 0, size, size);
		p.encodePNGToStream(img, passThroughStream).then(done);
	})

	return p.encodePNGToStream(canvas, stream);
}

```

### Platform
**OS:** Ubuntu 20.04.3 LTS
**Node Version:** 16.6.2
**NPM Version:**
**PureImage Version:** 0.3.5

### Any Additional Info

The main modification I've made to the original script is the p.decodePNGFromStream step. Given that avatars are saved with the correct backgrounds I believe the error lies somewhere in those four lines, but I can't figure out what it is from the documentation. Thanks for your help, and sorry if this is a basic question.

**Comment by joshmarinacci** [comment]
I think the problem is async code.  p.decodePNGFromStream is a promise. The ctx.drawImage call happens in the 'then' clause. However, you are returning p.encodePNGToStream() at the bottom. That line happens immediately, before the drawImage call happens.  Change it to be something more like:

```
	return p.decodePNGFromStream(fs.createReadStream(`${_dirname}/img.png`)).then((img) => {
		ctx.drawImage(img, 0, 0, size, size);
		return p.encodePNGToStream(img, passThroughStream).then(done);
	})
```
