### ISSUE TITLE
Problem to create transparent polygons

### ISSUE THREAD

**Issue by bartbutenaers** [joshmarinacci/node-pureimage#128]
Dear,
just started few days ago with this wonderful library, but having problems to draw transparent polygons on top of a jpeg image.

Thanks in advance!!
Bart

### Expected Behaviour
I would like to create transparent polygons on top of a jpeg images, i.e. only draw the colored edges of the polygon.

![image](https://user-images.githubusercontent.com/14224149/143305097-47bccb25-b2a4-45a4-8cfc-5b4e897cb790.png)

### Actual Behaviour
My polygons are always filled with a color, so I can never see the image underneath:

![image](https://user-images.githubusercontent.com/14224149/143306905-fe4dd3b1-5b2a-470e-8617-604de561da82.png)

### Steps To Reproduce
In the code snippet below, a jpeg image arrives in my application as a NodeJs ***buffer***.
I have tried all kind of changes to this code, but unfortunately none of them solves my issue:
1. Used `ctx.fillStyle = "rgba(0,0,0,0)"`.
2. Used `ctx.fillStyle = "#00000000"`.
3. Removed `ctx.fill()`.

### Any Relevant Code Snippets
```js
// Decode the jpeg inside the NodeJs buffer
var jimg = jpeg.decode(someNodeJsBuffer);

// Load the jpeg in the PureImage 2d context
var pimg = pureimage.make(jimg.width, jimg.height);
var ctx = pimg.getContext('2d');
ctx.bitmap.data = jimg.data;

// Start the polygon
ctx.beginPath();
ctx.fillStyle = 'transparent';
ctx.strokeStyle = "#0000FF";
ctx.lineWidth = 4;

// Draw the polygon line per line
var previousPoint = null;
var polygon = [[79,192],[461,192],[461,1114],[79,1114]];
polygon.forEach(function(point) {
    if (previousPoint) {
        ctx.lineTo(point[0], point[1]);
    }                    
    ctx.moveTo(point[0], point[1]);
    previousPoint = point;
})

// End the polygon
ctx.closePath();
ctx.fill();
ctx.stroke();
}

// Convert the PureImage 2d context back to a jpeg image
msg.image = jpeg.encode(pimg,70).data;
```

### Platform
**OS:** Windows 10
**Node Version:** v12.19.0
**NPM Version:** 6.14.8
**PureImage Version:** 0.3.6

**Comment by joshmarinacci** [comment]
You are both filling and stroking the rectangle. Instead you should just call stroke() but not fill(). Does that fix it?

**Comment by joshmarinacci** [comment]
I take that back. That's not the problem. I just ran similar code with a transparent fill and it works like it should.  I copied your code and I can replicate the bug.  I think you are missing an 'else' clause in your polygon loop. Without the else it will do a moveTo and lineTo on *every* point.


```javascript
        polygon.forEach(function(point) {
            if (previousPoint) {
                ctx.lineTo(point[0], point[1]);
            } else {
                ctx.moveTo(point[0], point[1]);
            }
            previousPoint = point;
        })
```

**Comment by bartbutenaers** [comment]
Evening @joshmarinacci,

Awesome!!  That works fine now.  I had completely overlooked that error in my logic, because I was so focussed on the fillStyle value. 

I really appreciate your fast feedback and the time you have spent to investigate my code.
Keep up the good work!!!

Thanks a lot,
Bart

**Comment by joshmarinacci** [comment]
Always happy to help!
