### ISSUE TITLE
bezierCurveTo incorrect path when performing stroke

### ISSUE THREAD

**Issue by maltekosian** [joshmarinacci/node-pureimage#129]
### Expected Behaviour
Draw an oval
1.
![out](https://user-images.githubusercontent.com/1401648/145087942-bf2201dc-95f1-40f8-822b-1ae89075a01c.png)

### Actual Behaviour
draws a "flower"
1.
![out](https://user-images.githubusercontent.com/1401648/145087427-d0aa653e-5759-4e4b-a2ad-9f6d0745d6ae.png)

### Steps To Reproduce
```js
points = [
  246, 338, 246, 382,
  246, 414, 300, 414,
  366, 414, 366, 371,
  366, 338, 327, 338
];
ctx.strokeColor = '#000';
ctx.beginPath();
     ctx.moveTo(points[i].p[14], points[i].p[15]); //each bezierCurve strangely centers back to the start point moveTo! 
    ctx.bezierCurveTo(points[i].p[14], points[i].p[15],points[i].p[0], points[i].p[1], points[i].p[2], points[i].p[3]);
    ctx.bezierCurveTo(points[i].p[2], points[i].p[3],points[i].p[4], points[i].p[5], points[i].p[6], points[i].p[7]);
    ctx.bezierCurveTo(points[i].p[6], points[i].p[7],points[i].p[8], points[i].p[9], points[i].p[10], points[i].p[11]);
    ctx.bezierCurveTo(points[i].p[10], points[i].p[11],points[i].p[12], points[i].p[13], points[i].p[14], points[i].p[15]);
    ctx.stroke();
    // if one uses ctx.fill() instead this will be an oval though


```

![out_fill](https://user-images.githubusercontent.com/1401648/145088769-ef8c606d-c4a3-428d-8db3-3f08c55a2d2a.png)    

### Platform
**OS:** windows 11
**Node Version:** 17.0.1
**NPM Version:** latest
**PureImage Version:** latest

### Any Additional Info
similar behavior for ctx.quadraticCurveTo but this mostly not strokes at all.

**Comment by joshmarinacci** [comment]
Could you give me the full code to reproduce this?  The 'i' variable is missing in your code above, and points is an array of numbers, not objects with a 'p' field on them.

**Comment by joshmarinacci** [comment]
I think I figured it out.  The flatten_path is supposed to update the 'curr' variable in every segment of the path, but it wasn't doing so for the Bezier curves.  Can you test if the change above fixes it for you?  Up can just add the one line above in the diff.

**Comment by maltekosian** [comment]
I will do reinstall pureimage and test the complete code tomorrow aka later during daytime today.
Sorry for the incomplete copy and paste code example.

**Comment by maltekosian** [comment]
I think the bug is fixed. Thank you very much. It would be nice to find the fix in the next master.

**Comment by joshmarinacci** [comment]
I've committed it to master and pushed out a patch release. See release 0.3.7 on NPM.  Good luck!

**Comment by maltekosian** [comment]
While the patch is part of the source (src/context.js flatten_path), strangely it is not part of the build (dist/pureimage-umd.cjs flattem_path). If one is using bezierCurveTo still the result are gloves/flowers but not wobbely ovals.

**Comment by joshmarinacci** [comment]
Oops. I forgot to npm build before publishing. Fixed. Look for 0.3.8
