### ISSUE TITLE
Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by upupzealot** [joshmarinacci/node-pureimage#13]
Error message:
```
Block-scoped declarations (let, const, function, class) 
not yet supported outside strict mode
```

'let' declarations found in `src/pureimage.js` line 436~line 453
reaplce that with 'var' would fix this problem

**Comment by joshmarinacci** [comment]
Could you set up a test script that would run a filter to check for these sorts of issues? I'm working on a massive rewrite for version 2 (in the refactor branch) and having automated checks would be awesome.

-j

**Comment by upupzealot** [comment]
I don't think a test could solve that.
In my opinion,  there are two ways to prevent this problem from happen again:
1. use a format check tool, such as ESlint
2. use bable to converts all codes into a `dist` dir, which will be used in production

**Comment by joshmarinacci** [comment]
yes, that's what i was thinking of.  npm test would run several scripts. one to do linting, one to run unit tests.
