### ISSUE TITLE
pngjs dependency is very old

### ISSUE THREAD

**Issue by sokcuri** [joshmarinacci/node-pureimage#134]
### Description
node-pureimage using pngjs version is 3.3.1, this version is very old.
PNGJS bug causes "There are some read requests waiting on finished stream" when decodingPNGFromStream of some png files
current pngjs version: 6.0.0

https://github.com/lukeapage/pngjs

**Comment by solace** [comment]
@sokcuri Hi! How did you resolve that error?

**Comment by sokcuri** [comment]
Sorry to late answer, I'm used pngjs directly, thanks!
