### ISSUE TITLE
context.font TypeScript types declaration are wrong.

### ISSUE THREAD

**Issue by TIRTAGT** [joshmarinacci/node-pureimage#136]
### Expected Behaviour

1. TypeScript shows the ``context.font`` accepts string instead of Object

``node-pureimage`` expects the parameter to be a string : [node-pureimage/src/context.js # Line 199](https://github.com/joshmarinacci/node-pureimage/blob/2071c5544a9fa6ad14e57b6b7ae29f7f2530b68d/src/context.js#L199)

### Actual Behaviour

1. TypeScript shows the ``context.font`` accepts context.Font ( Look on ``Code Snippet #1`` for details regarding the object properties)

That object was defined on : [node-pureimage/types/context.d.ts # Line 18](https://github.com/joshmarinacci/node-pureimage/blob/2071c5544a9fa6ad14e57b6b7ae29f7f2530b68d/types/context.d.ts#L18)

### Steps To Reproduce

1. Create index.ts and use the ``Code Snippet #2`` as the file content.
2. TypeScript would then complain that ``Type 'string' is not assignable to type 'Font'.``

### Any Relevant Code Snippets

```js
--- Code Snippet #1 ---
{
    family: string;
    size: number;
}

--- Code Snippet #2 ---
import * as PureImageLibrary from 'pureimage';
let img = PureImageLibrary.make(280, 90, null);
let ctx: Context = img.getContext('2d');
ctx.font = { family: "Calibri Regular", size: 32 };
```

### Platform
**OS: Arch Linux (Kernel: 5.16.2-arch1-1)**
**Node Version: v17.2.0**
**NPM Version: v8.1.4**
**PureImage Version: v0.3.8**

### Any Additional Info

I recommend changing the TypeScript type declaration on [node-pureimage/types/context.d.ts # Line 149](https://github.com/joshmarinacci/node-pureimage/blob/2071c5544a9fa6ad14e57b6b7ae29f7f2530b68d/types/context.d.ts#L149) from :
```typescript
/**
* @param {Font} font
* @example ctx.globalAlpha = 1;
*/
set font(val: Font);
```

into :
```typescript
/**
* @param {string} font size and family name
* @example ctx.font = "32pt 'Calibri Regular'";
*/
set font(val: string);
```

since the function that handles the font parameter, only accept strings :
```javascript
/**
* @param {object} font
* @example ctx.globalAlpha = 1;
*/
set font(val) {
	const n = val.trim().indexOf(' ')
	const font_size = parseInt(val.slice(0, n))
	const font_name = val.slice(n).trim()

	this._font.family = font_name;
	this._font.size   = font_size;
}
```

or.....  implements the Type object on the actual javascript code :
```javascript
/**
* @param {object} font
* @example ctx.globalAlpha = 1;
*/
set font(val) {
	if (typeof val == "object") {
		this._font.family = val.family.trim();
		this._font.size = val.size.trim();
	}
	else {
		const n = val.trim().indexOf(' ')
		const font_size = parseInt(val.slice(0, n))
		const font_name = val.slice(n).trim()

		this._font.family = font_name;
		this._font.size = font_size;
	}
}
```

and then changing the TypeScript declaration to be :
```typescript
/**
* @param {string} font size and family name
* @example ctx.font = "32pt 'Calibri Regular'"; or ctx.font = { family: "Calibri Regular"; size: "32pt"; }
*/
set font(val: Font | string);
```

**Comment by k2xl** [comment]
Note this is still an issue. Any other way to set a font besides the setter?

**Comment by joshmarinacci** [comment]
I've just fixed the type def to show that it's a string.

**Comment by k2xl** [comment]
@joshmarinacci thanks, is this pushed up on NPM?

**Comment by joshmarinacci** [comment]
I just pushed 0.3.9 with this fix.
