### ISSUE TITLE
table for richtext

### ISSUE THREAD

**Issue by anhoev** [joshmarinacci/node-pureimage#14]
Hi, can you add a feature for richtext: table (without border).
Thank you

**Comment by joshmarinacci** [comment]
I don't think so. The rich text was really just a demo to show that styled text would be possible with the font system. If you want something as complex as tables then you should probably use for a headless web renderer like Phantom.

-j

**Comment by joshmarinacci** [comment]
I have removed rich text support since it is not part of the canvas spec.
