### ISSUE TITLE
how to embed the image which i have just created with the message?

### ISSUE THREAD

**Issue by Nit-nit** [joshmarinacci/node-pureimage#147]
```js
client.on('messageCreate', (message) => {
  const img1 = PImage.make(100, 100)
  const ctx = img1.getContext('2d');
  ctx.fillStyle = 'red';
  ctx.fillRect(0,0,100,100);
  const attachment = new AttachmentBuilder();

  if (message.content.toLowerCase() === 'image') {
    const png = PImage.encodePNGToStream(img1, fs.createWriteStream('out.png'))
    .then(() => {
      message.reply(files [`${png}`])
    })
  }
});
```

**Comment by joshmarinacci** [comment]
I'm not sure. Is this a part of the Discord app? To use PureImage you'd need a way to import the library into the app.

**Comment by Le-Roux-nard** [comment]
*node-canvas is a famous image manipulation lib that is used a lot with discord.js (wrapper for discord API in Node.JS)*

In node-canvas we can export any image bitmap with `image.toBuffer()` and I think that what @Nit-nit tried to say was "Is there a way to do the same thing here without creating a file ?"

**Comment by Nit-nit** [comment]
> *node-canvas is a famous image manipulation lib that is used a lot with discord.js (wrapper for discord API in Node.JS)*
> 
> In node-canvas we can export any image bitmap with `image.toBuffer()` and I think that what @Nit-nit tried to say was "Is there a way to do the same thing here without creating a file ?"

yes, i mean "how to make your discord bot send the file in a message by embedding it without saving it on my device?"

**Comment by Nit-nit** [comment]
how does `image.toBuffer()` function work? can i have a code block? 🤪 lol

**Comment by joshmarinacci** [comment]
I updated the readme with an example that shows how to read an image from a URL and then process it in memory. Does that answer your question?
