### ISSUE TITLE
ctx.restore() doesn't appear to clear clipping region.

### ISSUE THREAD

**Issue by solace** [joshmarinacci/node-pureimage#148]
### Expected Behaviour

1. For the clipping region to be cleared.

### Actual Behaviour

1. Clipping region persists and renders to the canvas outside of the region are not displayed. 

### Steps To Reproduce

1. Sandbox at https://codesandbox.io/s/node-js-test-forked-kxp643
  Navigate to `/image` to trigger download of generated image. A circle should be rendered around the circle cropped image as well as text, but neither are visible.

### Any Relevant Code Snippets

The clipped region render code and outline that should be rendered on top.

```
ctx.save();
  ctx.beginPath();
  ctx.arc(
    SETTINGS.marginX + SETTINGS.iconSize / 2,
    SETTINGS.marginY + SETTINGS.iconSize / 2,
    SETTINGS.iconSize / 2,
    0,
    2 * Math.PI,
    false
  );
  ctx.clip();
  ctx.drawImage(
    icon,
    0,
    0,
    icon.width,
    icon.height,
    SETTINGS.marginX,
    SETTINGS.marginY,
    SETTINGS.iconSize,
    SETTINGS.iconSize
  );
  ctx.restore();
  ctx.strokeStyle = "#ffffff";
  ctx.strokeWidth = 2;
  ctx.stroke();
```

### Platform
**OS:** MacOS
**Node Version:** 18 and whatever is used on codesandbox
**NPM Version:** 8.1.3, 8.19.2
**PureImage Version:** ^0.3.14 

### Any Additional Info

With `ctx.clip()`, the resulting image looks like this with the intended circular border around the image cut off, and text is not visible.

![test (7)](https://user-images.githubusercontent.com/374583/197331481-ed3aac25-1b65-4a50-b27b-87feffd240d0.jpg)

With `ctx.clip()` commented out, the resulting image looks like this, but the image hasn't been rounded.

![test (11)](https://user-images.githubusercontent.com/374583/197331642-262ac00c-cdbd-4ac9-98bc-ab9e59f5d6e9.jpg)

I admit it's been a while since I've done work with canvas so I may be using the clipping and save/restore syntax incorrectly. I have worked around this issue by moving the clipping code after everything else has been rendered and adjusting offsets to account for the outline, but it'd be good to confirm if I've mucked up the save/restore or if there's an actual bug.

I am also uncertain if this console message which displays on render is problematic or just a warning:

```
can't project the same paths 1 [ 'l', Point { x: 295, y: 172.5 } ] Point { x: 295, y: 172.5 } Point { x: 295, y: 172.5 }
```

Thanks!

**Comment by joshmarinacci** [comment]
I was not able to view your example. It crashes with (node:74) UnhandledPromiseRejectionWarning: Error: Could not load font: Error: ENOENT: no such file or directory, open '/sandbox/src/fonts/Jost-400-Book.ttf'

**Comment by joshmarinacci** [comment]
I am able to confirm that the clip is not saved or restored properly.

**Comment by joshmarinacci** [comment]
I've pushed back a fix. Please test the latest release: 0.3.15

**Comment by joshmarinacci** [comment]
Does the current release fix the issue for you? Please reopen this bug if it doesn't.
