### ISSUE TITLE
support reading large files

### ISSUE THREAD

**Issue by Elastic1** [joshmarinacci/node-pureimage#149]
This error occurs when large JPEG files are loaded.
 ```Error: maxMemoryUsageInMB limit exceeded by at least 36MB``` 

Related: https://github.com/oliver-moran/jimp/issues/915

**Comment by joshmarinacci** [comment]
There aren't any direct memory limits in PureImage but NodeJS itself does. [This article](https://stackoverflow.com/questions/34356012/how-to-increase-nodejs-default-memory) has instructions to increase it.

**Comment by Elastic1** [comment]
This is a memory limitation in the `jpeg-js` library. 
Passing the `maxMemoryUsageInMB` option on this [line](https://github.com/joshmarinacci/node-pureimage/blob/master/src/index.js#L124) would fix the error.

(The max-old-space-size option did not work)

**Comment by joshmarinacci** [comment]
I've updated the api to let you pass options to the JPEG decoder
