### ISSUE TITLE
drawImage. RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by spelsinx** [joshmarinacci/node-pureimage#160]
### Expected Behaviour
A photo from the site on which the photo of the car is in png format. 

### Actual Behaviour
Does not work. 

### Steps To Reproduce 
/home/base/imagegen/node_modules/pureimage/dist/pureimage-umd.cjs:7437
        drawImage(bitmap, sx,sy,sw,sh, dx, dy, dw, dh) {
                 ^

RangeError: Maximum call stack size exceeded

### Any Relevant Code Snippets

```js
import * as PImage from "pureimage"
import * as fs from 'fs'
import * as client from "https"

// get canvas context

let url = "https://vr.josh.earth/webxr-experiments/physics/jinglesmash.thumbnail.png"
let filepath = "out.png"

const font = PImage.registerFont('SourceSansPro-Regular.ttf','MyFont');
// fill with red

//write to 'out.png'
font.load(() => {
	client.get(url, (image_stream)=>{
		
PImage.decodePNGFromStream(image_stream).then(img => {
	// fill with red
	const ctx = img.getContext('2d');
	ctx.drawImage("car.png", 350, 550);
	PImage.encodePNGToStream(img, fs.createWriteStream(filepath)).then(()=>{
    console.log("wrote out the png file to out.png");
}).catch((e)=>{
    console.log("there was an error writing");
})
})
})
})
```

### Platform
**OS: Android**
**Node Version: v19.4.0**
**NPM Version: v9.2.0**
**PureImage Version: v0.3.14**

### Any Additional Info

absent

**Comment by spelsinx** [comment]
I won't get help, as i understand it?

**Comment by joshmarinacci** [comment]
Apologies. I don't think I ever saw this issue before.  The drawImage code was overhauled recently. Does it still happen for you? Also I notice you are passing a string to drawImage, which doesn't make sense. That would fail on any Canvas implementation.
