### ISSUE TITLE
Transparent background

### ISSUE THREAD

**Issue by stevage** [joshmarinacci/node-pureimage#165]
It doesn't seem possible currently to create an image with a transparent background, since the background is automatically filled with black.

Transparent background PNGs are pretty useful!

**Comment by stevage** [comment]
This workaround works:


```
    for (let i = 0; i < ctx.bitmap.width; i++) {
        for (let j = 0; j < ctx.bitmap.height; j++) {
            ctx.bitmap.setPixelRGBA(i, j, 0);
        }
    }
```

Btw according to my reading of the spec, the canvas by default should be transparent. It should only be black if initialised with `{ alpha: false }` as the third argument.

**Comment by joshmarinacci** [comment]
I just merged a PR to fix compositing with transparent pixels. Does this fix the issue for you?
