### ISSUE TITLE
[feature request] setting the encode option (e.g. PNG compression level)

### ISSUE THREAD

**Issue by Pomax** [joshmarinacci/node-pureimage#172]
### Expected Behaviour

1. The canvas API lets you set the PNG compression level, I expected `encodePNGToStream` to have an optional argument to do the same.

### Actual Behaviour

1. You get no choice in compression level

### Steps To Reproduce

1. None

### Any Additional Info

https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL#parameters

**Comment by joshmarinacci** [comment]
PNG is lossless, so I don't think it has compression levels. Jpeg does, and we support a quality setting.

**Comment by Pomax** [comment]
It very much does, because it's lossless gzip compression, and gzip has 9 levels of compression.

**Comment by joshmarinacci** [comment]
I added optional parameters that match the compression level and type from the underlying PNGJS encoder. Does this work for you?

**Comment by Pomax** [comment]
awesome, yes: thank you so much!
