### ISSUE TITLE
Can this run on the browser?

### ISSUE THREAD

**Issue by Sharcoux** [joshmarinacci/node-pureimage#173]
It's been years that I'm looking for a pure js implementation of a canvas that could work cross-platform and without some limitations that exist in the HTML canvas api. However, I'm not sure if this lib can still run in the browser. If it can, then I didn't succeed to make it work. I get `ReferenceError: exports is not defined`. This might be due to a misconfiguration of my webpack config, but I just want to be sure that it can really work.

**Comment by joshmarinacci** [comment]
Yes, it should run in the browser, though I don't know why you'd want to. The browser's own Canvas impl will be much faster.  If it's not loading then that must be a build error. Are you importing it as common JS or ESM modules?

**Comment by Sharcoux** [comment]
As commonJS I believe. I'll dive into the build process. I'm not so comfortable with babel/webpack/ts transpilation process, but I'll try to figure it out. I just wanted to be sure the problem was coming from me.

Anyway, you really did a great job if you succeeded to do a cross-platform implementation of the canvas api. Many projects tried to do it and all of them failed until now. This should be able to solve many problems in React Native. In my current case, I need to work around some security restrictions pushed by the web canvas api, but I'm not sure that this approach can work anyway.

Thanks for your answer.

**Comment by McMelonTV** [comment]
Hey, have you managed to get this to work with React Native?
