### ISSUE TITLE
make() is deprecated

### ISSUE THREAD

**Issue by Javarome** [joshmarinacci/node-pureimage#181]
### Expected Behaviour

1. When using make(), see in the JSDoc which alternative API is recommended.

### Actual Behaviour

1. When using make, one can see that it is deprecated but with no doc as the recommended alternative.

### Steps To Reproduce

1. use make() in an IDE.

**Comment by joshmarinacci** [comment]
I just fixed a bunch of typescript and doc bugs. Can you confirm that this is fixed for you in release 0.4.10?

**Comment by joshmarinacci** [comment]
First I want to say I had no idea how many people are using PureImage and I'm very sorry I broke it.

Next: The source of the breakage was me trying to set up a CI system with Github Actions.  

I've just published 0.4.13. Could you try that out and let me know if that fixes it?
