### ISSUE TITLE
Error [ERR_MODULE_NOT_FOUND]: Cannot find package in version 0.4.11

### ISSUE THREAD

**Issue by dev-blinq** [joshmarinacci/node-pureimage#187]
### Expected Behaviour

1. Import of the latest 0.4.11 pureimage version will work
This issue doesn't reproduce in version 0.4.9
### Actual Behaviour

1. when running a package that uses pureimage 0.4.11 I'm seeing the following error:
Error [ERR_MODULE_NOT_FOUND]: Cannot find package '<my project>/node_modules/pureimage/' imported from <my project>/src/client/scenario_report.js
    at new NodeError (node:internal/errors:387:5)
    at legacyMainResolve (node:internal/modules/esm/resolve:242:9)
    at packageResolve (node:internal/modules/esm/resolve:839:14)
    at moduleResolve (node:internal/modules/esm/resolve:901:20)
    at defaultResolve (node:internal/modules/esm/resolve:1115:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:841:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

### Steps To Reproduce

1. Just import it to node project:
import * as PImage from "pureimage";

### Any Relevant Code Snippets

```js

```

### Platform

**OS:MAC
**Node Version:v20.6.1
**NPM Version:9.8.1
**PureImage Version:0.4.11

**Comment by codeandcats** [comment]
@joshmarinacci I believe `pureimage` was somehow accidentally published to npm without doing a build first as the dist folder [is not present](https://unpkg.com/browse/pureimage@0.4.11/) in version `0.4.11`.

**Comment by joshmarinacci** [comment]
First I want to say I had no idea how many people are using PureImage and I'm very sorry I broke it.

Next: The source of the breakage was me trying to set up a CI system with Github Actions.  

I've just published 0.4.13. Could you try that out and let me know if that fixes it?

**Comment by joshmarinacci** [comment]
I just made a little test app with this package.JSON

```JSON
{
  "name": "import_example",
  "version": "1.0.0",
  "description": "",
  "main": "basic.js",
  "type": "module",
  "scripts": {
    "test": "node basic.js"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "pureimage": "^0.4.13"
  }
}
```

and this code in javascript:

```javascript
import * as PImage from "pureimage";
import * as fs from "fs";
const img1 = PImage.make(100, 100);
const ctx = img1.getContext("2d");
ctx.fillStyle = "red";
ctx.fillRect(0, 0, 100, 100);

PImage.encodePNGToStream(img1, fs.createWriteStream("out.png"))
    .then(() => {
        console.log("wrote out the png file to out.png");
    })
    .catch((e) => {
        console.log("there was an error writing", e);
    });
```

And it worked fine.

**Comment by joshmarinacci** [comment]
Since I haven't heard back and the new packaging seems to be working, I'm going to close this issue.
