### ISSUE TITLE
NPM version 0.4.11 is missing the dist folder.

### ISSUE THREAD

**Issue by Kilian** [joshmarinacci/node-pureimage#188]
The publishing of version 0.4.11 went wrong and now there is no dist folder: 

https://www.npmjs.com/package/pureimage/v/0.4.11?activeTab=code

_This is essentially the same issue as https://github.com/joshmarinacci/node-pureimage/issues/187 but a little more direct._

**Comment by joshmarinacci** [comment]
Thanks for figuring this out.  First I want to say I had no idea how many people are using PureImage and I'm very sorry I broke it.

Next: The source of the breakage was me trying to set up a CI system with Github Actions.  

I've just published 0.4.13. Could you try that out and let me know if that fixes it?

**Comment by Kilian** [comment]
0.4.13 works fine!
