### ISSUE TITLE
fillText problem

### ISSUE THREAD

**Issue by niumowangorz** [joshmarinacci/node-pureimage#191]
After the fillText method sets the xy parameter, the string is written from above the coordinate point, while the html native canvas writes the string from below the coordinate point. Why is that?

**Comment by joshmarinacci** [comment]
Hmm. That shouldn't be the case. Can you send me a code sample that shows the behavior?

**Comment by niumowangorz** [comment]
![1697702681005](https://github.com/joshmarinacci/node-pureimage/assets/32349095/65b281d3-2afc-4f56-b31d-9311db648d7e)

Thank you for your reply. When I use canvas in html environment, xy of fillText method is set to 50 and 80, and the effect displayed is yellow area on the way, but when I use canvas in node-pureimage, it is green area. I don't know whether it is intentionally or for other reasons.

**Comment by joshmarinacci** [comment]
No problem. Happens to me all the time.
