### ISSUE TITLE
Drawing doesn't work correctly

### ISSUE THREAD

**Issue by MasterPtato** [joshmarinacci/node-pureimage#20]
I am trying to draw a pixel on my 100x100 image, but it comes out as a really big box, and the position isn't even correct. Here is all the code i used for drawing it (import, draw, and export):

```
var canvas;
pimg.decodePNG(fs.createReadStream('canvas.png'),cb=>{
	canvas = cb;
});

var c = canvas.getContext('2d');

c.fillStyle = 'rgba(0,100,100,1)';
c.fillRect(4,4,1,1);

pimg.encodePNG(canvas, fs.createWriteStream('canvas.png'),err=>{
	console.log(err)
});
```

my result: [image](http://i.imgur.com/Lfo5Xm7.png)

**Comment by joshmarinacci** [comment]
Hi there. You are invoking the drawing code before the source image is actually loaded. You'll need to move the drawing code to be inside the callback.  Can you see if it works then?

something like pimg.decodePNG(fs.createReadStream(), canvas => {
    var c = canvas.getContext('2d');
   c.fillStyle = 'red';
   c.fillRect(4,4,1,1);
   pimg.encodePNG(canvas...
}

**Comment by MasterPtato** [comment]
You were right about the source not being loaded. I added a very small setTimeout and it works perfectly now. Thank you
