### ISSUE TITLE
context.canvas property is missing

### ISSUE THREAD

**Issue by kekscom** [joshmarinacci/node-pureimage#203]
### Expected Behaviour

1. _context.canvas_ property is present

### Actual Behaviour

1. It's undefined.

### Steps To Reproduce

1. Just inspect context.canvas

### Platform

**OS: macOS**
**Node Version: 20.x**
**NPM Version:**
**PureImage Version: 0.4.13**

### Any Additional Info

This is useful when passing the context elsewhere and referring to some original canvas properties such as width, height

**Comment by joshmarinacci** [comment]
I just added a read only `canvas` property to the context object. It points to the bitmap object that the context draws to. This is live in the new 0.4.15 release.
