### ISSUE TITLE
Is there a way to retrieve to output the image data into base64 ?

### ISSUE THREAD

**Issue by manelephant** [joshmarinacci/node-pureimage#205]
Hello,

Your "no-dep" library look really great for my use-case.

The thing is that i have to create the image then attach it to an email (base64 data string) and not stored it anywhere.

Maybe you or someone know how i can do this.

Thank you !!!

**Comment by joshmarinacci** [comment]
I'm pretty sure base64 can be done using a node buffer. Something like buffer.toString("base64")

Josh Marinacci
Recovering Eng

Sent via Superhuman iOS ( ***@***.*** )

**Comment by joshmarinacci** [comment]
I just added an example to the readme.
