### ISSUE TITLE
canvas-webworker

### ISSUE THREAD

**Issue by indus** [joshmarinacci/node-pureimage#21]
Can you compare your project to https://github.com/casperlamboo/canvas-webworker?

**Comment by joshmarinacci** [comment]
I haven't used this other library so I can't really compare. It looks like it is targeted strictly for use inside the browser. PureImage is targeted for use inside NodeJS, so it includes PNG, JPG, and TTF support.

**Comment by indus** [comment]
Thanks for the info.
