### ISSUE TITLE
Example help?

### ISSUE THREAD

**Issue by ScottChapman** [joshmarinacci/node-pureimage#22]
I am wanting to use pureimage to be able to open a JPG file and draw a rectangle (like as part of face-detection or similar). 

I am using google vision APIs to identify faces, and I get rectangle coordinates. I just need help drawing the rectangle on the image.

Thanks in advance!

**Comment by joshmarinacci** [comment]
Sure. Basically you just need to load the image then get a context so you can draw on it, then save it back. Something like this (I haven't actually tried to compile this yet).

```
var rect = ....
PImage.decodeJPG(fs.createReadStream(path), function(img) {
   var c = img.getContext('2d');
   c.strokeStyle = "black";
   c.strokeRect(rect.x, rect.y, rect.w, rect.h);
   PImage.encodeJPG(img, fs.createWriteStream(path), function(err) {
     console.log("wrote out the image");
  });
});
```

**Comment by ScottChapman** [comment]
That got be further, but I am getting an error decoding the JPG:
SOI not found.

Any ideas? I can shoot you the image if you are interested. Appears to be an OK image.

**Comment by joshmarinacci** [comment]
Can you send me the image?

**Comment by ScottChapman** [comment]
Never mind, realized that it didn't work with fs streams. Converted the readStream to a readFileSync and I got the file decoded alright.

What would the equivalent be for the encode?

**Comment by ScottChapman** [comment]
Maybe the above isn't actually right. Looks like your code does use streams.

**Comment by ScottChapman** [comment]
yea, so I can decode with jpeg.js like this: https://github.com/eugeneware/jpeg-js#decoding-jpegs

But I can't decode using stream with pureimage

**Comment by ScottChapman** [comment]
OK got it. I was close; you do need to pass in the data from the file (readFileSync for example). And it RETURNS the image:
```
  var PImage = require('pureimage');
	var img = PImage.decodeJPEG(fs.readFileSync('./image.jpg'));
		console.dir(img);
   var c = img.getContext('2d');
	 console.dir(c);
   c.strokeStyle = "black";
   c.strokeRect(rect.x, rect.y, rect.w, rect.h);
   PImage.encodeJPEG(img, fs.createWriteStream('./image2.jpg'), function(err) {
     console.log("wrote out the image");
  });
```

**Comment by ScottChapman** [comment]
@joshmarinacci - out of curiosity, how can I control stroke width?

**Comment by brainlessboy** [comment]
lineWidth does not work, just tested ... is there a way to set lineWidth?

**Comment by ColineDoe** [comment]
Same problem here lineWidth does not work

**Comment by joshmarinacci** [comment]
lineWidth has not been implemented. It's trickier than it sounds to build. Essentially we need to calculate a new path by extruding the old path to the line width, then render this new filled in path. I'll take a look at it this weekend.  In the mean time, what are you actually trying to do? There might be another way to do it.

**Comment by brainlessboy** [comment]
yes, agree lines are science of their own :-) for horizontal and vertical lines or rectangles or circles there are fair and easy workarounds, every thing else requires more vector math, i am sure you considered this https://en.wikipedia.org/wiki/Bresenham%27s_line_algorithm. for what i am trying to your library is  perfect as it is now, i really only need to draw rectangles with various line width, so that part was actually really easy to workaround (two filled rectangles no big deal). but i really like the idea of having a complete serverside standalone canvas library or graphic libraries in general. thanks for making this.

**Comment by joshmarinacci** [comment]
The code already uses bresenham for drawing lines, but that only works for single pixel width lines.  However, I have a plan.

There is no way to calculate a curve at a fixed offset from another curve, but in node-pureimage all curves are flatted into lines before drawing. I think if lineWidth is > 1, then it could calculate a new polygon by drawing two new lines parallel to the original, then fill that new path.  Worth an experiment, anyway.

I'm glad you like the library.  Out of curiosity, what are you using it for?

**Comment by brainlessboy** [comment]
... i needed a quick solution to generate comic book panels, doing all variations manually would take days or weeks, with a bit of code and your library i was able to do all the variations including the possibility to adapt them instantly to other resolutions in just one day ... (i use them for e-readers resolution or ipad resolution and also for higher print resolution) this way i was able to remove that repetitive task of drawing the panels ...

**Comment by joshmarinacci** [comment]
How cool! Thank you for sharing.
