### ISSUE TITLE
fillRect does not process RGBA

### ISSUE THREAD

**Issue by nbonamy** [joshmarinacci/node-pureimage#24]
Hello,

I was trying to fillRect with a rgba fillStyle but my image gets filled with the rgb value without taking transparency into account.

Looking at composite implementation, I am not that surprised :)

```
composite(i,j,old_pixel, new_pixel) {
  return new_pixel;
}
```

Seems like that a dependency to [color-composite](https://github.com/colorjs/color-composite/blob/master/index.js) could be used.

Thanks,
Nicolas

**Comment by joshmarinacci** [comment]
Hi Nicolas.  Yes, compositing is not implemented yet. However, rgba fills *should* be working. I just built a quick test using 
ctx.fillStyle = 'rgba(255,0,0,0.5)';
and it is 50% transparent.  What code are using?

-j

**Comment by joshmarinacci** [comment]
I was wrong. It only worked in very specific cases. I've just implemented proper alpha compositing for globalAlpha and rgba() colors, for the SRC_OVER blend mode. Please test the new code and tell me what bugs you see.
