### ISSUE TITLE
Console.log pollution with fonts.

### ISSUE THREAD

**Issue by Cykon** [joshmarinacci/node-pureimage#25]
The new version of the library is polluting the console with additional font information. 

Example:

PureImage loading Open Sans undefined undefined undefined
searching for font  Open Sans
font not found:  Open Sans
instead trying family Open Sans

**Comment by joshmarinacci** [comment]
Sorry about that. I just pushed a new npm version which removes those

**Comment by Cykon** [comment]
Awesome, thanks, it's fixed now!
