### ISSUE TITLE
Timeline for clip and other missing features?

### ISSUE THREAD

**Issue by geuis** [joshmarinacci/node-pureimage#26]
Was looking at pureimage as a replacement for node-canvas, but hit the wall when I found things like `clip` weren't supported yet. https://github.com/joshmarinacci/node-pureimage/blob/master/src/context.js#L211

Any idea when the rest of the canvas api will be built out in pureimage?

**Comment by joshmarinacci** [comment]
I plan to fill out compositing next week. What other features do you need? Clip rect or any shape clipping?

**Comment by geuis** [comment]
Cool. Yeah, any shape clipping. `moveTo`, `lineTo`, and `context.clip`.

**Comment by joshmarinacci** [comment]
I've just published my first attempt at clip() support. Please test it and tell me what bugs you find. thx.

**Comment by joshmarinacci** [comment]
Did this work for you?
