### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by robertmain** [joshmarinacci/node-pureimage#32]
Just a note to say that it would be nice to have access to API documentation on how to use things that aren't covered in the README like low-level API methods etc.

I'm happy to help out with this in setting up jsdoc and some kind of build system for you, but I don't know exactly how everything is meant to work so I'd need some help :)

**Comment by upupzealot** [comment]
@joshmarinacci we need doc, and maybe @robertmain can help

**Comment by joshmarinacci** [comment]
Yes, I would love some help @robertmain . I started a new job and haven't had much time to work on PureImage.

**Comment by robertmain** [comment]
What is the repo written in? It kinda looks like TypeScript, but there's no `tsconfig.json`

**Comment by joshmarinacci** [comment]
just plain javascxript

**Comment by robertmain** [comment]
Yeah - just edited my comment - sorry. Is it ES6?

**Comment by joshmarinacci** [comment]
yes, it should be

**Comment by robertmain** [comment]
Do you mind me setting up ESLint and doing a bit of a code tidy-up with it?

**Comment by joshmarinacci** [comment]
That would be great. Thank you!

**Comment by robertmain** [comment]
No problem - should make sure that any future contributions have a similar coding standard

**Comment by robertmain** [comment]
By the way, this is going to be a team effort because I don't know this codebase very well and some of the variable names aren't immediately obvious as to what they represent. With that in mind, this may want some revision before merging :)

I'm also adding in a travis configuration file and some other goodies to make it easy to have this stuff automatically run on any pull requests and commits against the repo :)

**Comment by joshmarinacci** [comment]
Of course. I appreciate your help.  What does travis do? Unit tests?

**Comment by robertmain** [comment]
Travis basically does anything you want. It can run unit tests (I've configured it to run your `npm test` script. It can also automatically generate your documentation and throw it up on github pages or anywhere else you want. I have set this up already for a PHP library I built. http://robertmain.github.io/communique

**Comment by joshmarinacci** [comment]
Oh, that would be handy. Yes please.

- J

**Comment by robertmain** [comment]
Cool, well you'd need to create an account on http://travis-ci.com (they're free and it links up with GitHub), point it at your repo and it can build and test your PRs and commits. When you merge my documentation PR it will bring a tavis config file with it that should have everything (more or less) setup. You will need to do a bit of tweaking to get the documentation publication to GH pages working, but again - I'm happy to help with this :)

**Comment by robertmain** [comment]
Forgot to mention, I have a branch with `eslint` configured too so that can be added into the whole travis thing so that when people open pull requests it will lint the code and run the unit tests - then if/when you merge it will generate docs for you and whack them up on GH Pages :D

**Comment by robertmain** [comment]
@upupzealot @joshmarinacci my PR is ready for review/merge :)

**Comment by joshmarinacci** [comment]
I just merged both changes and I'm testing locally.   npm run test fails because tape is missing.  npm run docs fails because esdoc is missing.

**Comment by robertmain** [comment]
Tape and ESDoc are dev dependencies. `npm install --dev`

**Comment by robertmain** [comment]
Is it working now?

**Comment by robertmain** [comment]
If you want, I can help you setup Travis to publish the docs automatically for you :)

**Comment by joshmarinacci** [comment]
That would be great. I've gotten super busy at my new job.

**Comment by robertmain** [comment]
Hang tight...putting something together..

**Comment by robertmain** [comment]
@joshmarinacci Managed to get it working! Lemme put a PR together

**Comment by robertmain** [comment]
Looks like this has been taken care of by #39 and #42 so I'm gonna close this for now..
