### ISSUE TITLE
uint32

### ISSUE THREAD

**Issue by robertmain** [joshmarinacci/node-pureimage#33]
Just noticed that there is a copy of https://github.com/fxa/uint32.js in the pureimage. Would it not be better to pull this in via npm instead? That way, it's less code to be maintained by the repo maintainers...

**Comment by joshmarinacci** [comment]
It seemed like it was overkill to pull in something external that we don't ever want to change. Too often I've had external libs break when updating, and this didn't feel like something we ever wanted to change anyway.  Actually, we could probably trim it down to just the parts we need.

-J

**Comment by robertmain** [comment]
> Too often I've had external libs break when updating

Yeah, I know what you mean...https://www.npmjs.com/package/left-pad

> Actually, we could probably trim it down to just the parts we need.

Fair enough, it looks like it's more or less complete for docblocks, though ESDoc was choking on some parts of it, hence why I was considering pulling it out and using `npm` to bring it in externally
