### ISSUE TITLE
Extract complex data types

### ISSUE THREAD

**Issue by robertmain** [joshmarinacci/node-pureimage#34]
It might be beneficial to extract more complex data types that get passed around to an external file. The one that comes to mind particularly is the concept of a `line` object. 

The library expects that a line looks like this:

```js
{
    start: {
        x: 42,
        y: 30
    }, 
    end: {
        x: 10, 
        y: 20
    }
}
```

however, it's very difficult for both library consumers and any linters or parsers to know this. 

I don't mind putting in a PR to do this, with your approval...

**Comment by joshmarinacci** [comment]
that would be great.

**Comment by robertmain** [comment]
Since this has been merged, I'm going to close this
