### ISSUE TITLE
font family contains leading space

### ISSUE THREAD

**Issue by fmsy** [joshmarinacci/node-pureimage#37]
https://github.com/joshmarinacci/node-pureimage/blob/f287b12a18dde50ecc1e1560006a0787cf44766e/src/context.js#L117

if working with more than one font i have to register the font with a leading space in its family name.

i assume this to not be what its meant to.

**Comment by robertmain** [comment]
Can you provide code samples for this? Expected vs Actual?

**Comment by fmsy** [comment]
this is my current workaround:

```javascript
		var font_family = getFontFamilyPureimage(font_weight,font_family_index);
		ctx.font = font_size+' '+font_family;
		ctx._font.family = font_family;
```

lets assume font family to be `"Arial"`

`ctx._font.family` will contain `" Arial"` after the `ctx.font` assignment

**Comment by robertmain** [comment]
Looks fair enough to me me. FYI I can't merge your PR though because I don't have write access to the repo

**Comment by joshmarinacci** [comment]
looks good to me.

**Comment by joshmarinacci** [comment]
Please verify this is fixed with https://github.com/joshmarinacci/node-pureimage/pull/41
