### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by robertmain** [joshmarinacci/node-pureimage#43]
Can I look at straightening the tests out? I've already started to put something together locally - but (with your approval) I'll continue and start putting a branch (and ultimately) a PR together? :)

**Comment by joshmarinacci** [comment]
Absolutely! Thank you!

**Comment by robertmain** [comment]
Cool - I've had a look at using `jest` in the place of `tape`. Reason being is that (in my opinion) it produces better readable test output, it supports mocking and it's easier to configure (pretty much no config out of the box). 

The syntax looks like this:
```js
const Point = require('../../src/Point');
const Line  = require('../../src/Line');

describe('Line', () => {

    it('created from two points use them as start and end points', () => {
        let start = new Point(6, 8);
        let end   = new Point(12, 6);

        expect(() => new Line(start, end)).not.toThrow(TypeError);
        expect(() => new Line(6, 8)).toThrow();
    });

    it('created from 4 ordinates uses them as start and end points', () => {
        expect(() => new Line(6, 8, 12, 6)).not.toThrow();
        expect(() => new Line({}, "spaghetti", "hello world", [])).toThrow(TypeError);
    });

    it('can only be created with either 2 or 4 arguments', () => {
        let errorMsg = 'Please pass either two Point objects, or 4 integers to the constructor';

        expect(() => new Line()).toThrow(errorMsg);
        expect(() => new Line(12)).toThrow(errorMsg);
        expect(() => new Line(12, 30, 92)).toThrow(errorMsg);
        expect(() => new Line(12, 30, 92, 10, 99)).toThrow(errorMsg);
    });

    it('is the distance between two points', () => {
        let start = new Point(6, 8);
        let end   = new Point(0, 0);

        let line  = new Line(start, end);

        expect(line.getLength()).toBe(10);
    })
});
```

Which produces output that looks like this:
![image](https://user-images.githubusercontent.com/537684/33241758-7672cb88-d298-11e7-9479-35491a58bf0b.png)

**Comment by robertmain** [comment]
Forgot to mention - it also supports mocking too, which might be nice when dealing with dependencies between objects like `Context` and `Bitmap`

**Comment by robertmain** [comment]
@joshmarinacci  - I'm just busy converting some of the existing tests into unit tests...I was wondering what this did:

```js
var PImage = require('../src/pureimage');

{

    // compositing tests
    // red onto white
    eq(PImage.compositePixel(0xFF0000FF, 0xFFFFFFFF), 0xFF0000FF);
    // blue onto white
    eq(PImage.compositePixel(0x00FF00FF, 0xFFFFFFFF), 0x00FF00FF);
    // red onto black
    eq(PImage.compositePixel(0xFF0000FF, 0x000000FF), 0xFF0000FF);
    // red 50% onto black
    eq(PImage.compositePixel(0xFF00007F, 0x000000FF), 0x7F0000FF);
}

function eq(a,b) {
    if(a != b) throw new Error(a.toString(16) + " is not equal to " + b.toString(16));
}
function dumpBytes(img) {
    for(var i=0; i<10; i++) {
        console.log(i,img._buffer[i].toString(16));
    }
}
```

It's clearly testing the `compositePixel` method - but I'm not quite sure what that method does - I also can't seem to find it in the library anywhere...unless it's referring to the `composite` method in the `Bitmap` class?

**Comment by joshmarinacci** [comment]
Honestly I don't remember. An earlier version of pure image had a compositingPixel function, though it didn't work correctly.  You can just skip these for now. We'll make new ones.

-j

**Comment by robertmain** [comment]
OK, no problem. In the mean time if you have a sec - #42 and #39 are done and ready for review/merge :)

**Comment by joshmarinacci** [comment]
Sorry, it's busy season as we prepare for the Mozilla All Hands next week.

I just merged the pull requests. Thank you so much for all of your work.

-j

**Comment by robertmain** [comment]
haha, no problem - i know how it is :) 

not a problem - always happy to help out :D

**Comment by robertmain** [comment]
Oh by the way - I just looked at https://travis-ci.org/joshmarinacci/node-pureimage and it says it's not an active repo. Have you enabled travis because it looks like it's not running the build

**Comment by joshmarinacci** [comment]
I just made it active and triggered a build.

https://travis-ci.org/joshmarinacci/node-pureimage <https://travis-ci.org/joshmarinacci/node-pureimage>

**Comment by robertmain** [comment]
Looks like you're missing the `GITHUB_TOKEN` environment var from Travis. Take a look at the pre-requisites here: https://github.com/joshmarinacci/node-pureimage/pull/39#issue-275880710 :)

Also - you might want to consider adding a link to `http://joshmarinacci.github.io/node-pureimage` at the top of your README for the documentation :)

Also - travis should let you rerun the failed build

**Comment by joshmarinacci** [comment]
I just set up the token and ran it again. Interestingly, this time two of the builds worked but one didn't. 1.1 and 1.3 worked but 1.2, the one with node 7, failed. 

-j

**Comment by robertmain** [comment]
Odd - I took a look and it's mentioning that it couldn't push to `gh-pages`. It looks like it was saying that it couldn't push to `Couldn't push the build to github.com/joshmarinacci/node-pureimage.git:gh-pages`. I wonder if maybe the branch didn't exist at that point or something.

Try re-running the individual job again - if that still doesn't do it, you may have to raise an issue with Travis. Either way - looks like the docs are online! http://joshmarinacci.github.io/node-pureimage

**Comment by robertmain** [comment]
This looks like it _might_ be related to https://github.com/travis-ci/travis-ci/issues/8548

**Comment by robertmain** [comment]
@joshmarinacci 

I emailed Travis support yesterday and they wondered if it might be because all 3 jobs are trying to do the deploy...can you try adding `node: $TRAVIS_NODE_VERSION` after line 18 of .travis.yml?

Like so:
```yml
language: node_js
node_js:
    - "node"
    - "7"
    - "8"
install: npm install
script:
  - npm run-script docs
deploy:
  overwrite: true
  provider: pages
  file_glob: true
  file: docs/*
  local_dir: docs
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
    node: $TRAVIS_NODE_VERSION
```

**Comment by joshmarinacci** [comment]
it looks like all of this was done.
