### ISSUE TITLE
Use an external drawing library?

### ISSUE THREAD

**Issue by Zubnix** [joshmarinacci/node-pureimage#44]
Hi all,

A while back I was looking for a canvas/drawing library that doesn't depend on any native code and that could run in both node & browser (webworker). I came across this project but noticed that was severely lacking in (advanced) drawing functionality. Quite normal given the absolutely monumental task of implementing such a thing.

Anyway, in the meantime I discovered [Skia](https://skia.org/) (which is actually the library used by browsers to implement their canvas operations), and [ported it to wasm](https://github.com/Zubnix/skia-wasm-port). Including a basic set of working bindings.

Purely as a suggestion, perhaps it would be interesting to implement the canvas operations of this project using the skia wasm port as it would most likely yield far better performance, as well as having near all drawing operations already available to you, while still being 100% js compatible/no native code.

**Comment by robertmain** [comment]
So, you're proposing say - replacing the contents of [this method](https://github.com/joshmarinacci/node-pureimage/blob/master/src/context.js#L682-L685) with a call to Skia instead?

**Comment by Zubnix** [comment]
Pretty much.

https://fiddle.skia.org/c/4a77165359d7479f0e1c5d38fd7e1ec5

I guess the current js could be implemented by several (2?) path commands. The rest is boilerplate.

**Comment by robertmain** [comment]
That does sound kinda cool. I'm doing a fair bit of work on the lib at the moment (for example getting the docs to auto generate here: http://joshmarinacci.github.io/node=pureimage). I'm also putting some unit tests together in [jest](https://www.npmjs.com/package/jest) to replace the (currently broken) ones written in [tape](https://www.npmjs.com/package/tape).  This is getting worked on in #43.

With that in mind - I'd appreciate some help coming up with tests. You can see below the scenarios that I've managed to write tests for:
![image](https://user-images.githubusercontent.com/537684/34643260-4fd45ee8-f2ef-11e7-9d78-eebf6a75a1e1.png)

However - you can also probably guess that the library is nowhere near fully covered with tests yet...
![image](https://user-images.githubusercontent.com/537684/34643266-64c743ba-f2ef-11e7-8d85-dad8d44baa5f.png)

Perhaps when it is - we could come up with a PR to replace the JS with `skia` using the tests to back up the refactor? :)

**Comment by joshmarinacci** [comment]
we will never delegate to skia or another native drawing api.
