### ISSUE TITLE
measureText is not working

### ISSUE THREAD

**Issue by Fuzzyma** [joshmarinacci/node-pureimage#51]
`measureText` is not working because it searches for a `_settings` property in `ctx` which is not there.
Instead it should use `_font` not `_settings.font`.

When this is fixed it still does not find the font because the font is saved in the wrong format (see #50 )

**Comment by joshmarinacci** [comment]
This should be fixed now. I've added a unit test too! Can you test if it works for you?

**Comment by joshmarinacci** [comment]
Did the new version work for you?

**Comment by Fuzzyma** [comment]
Sorry couldn't test it.
