### ISSUE TITLE
utf8 font support

### ISSUE THREAD

**Issue by mohsenxad** [joshmarinacci/node-pureimage#55]
### Expected Behaviour

Unicode and rtl languages  support on fillText methof
text like سلام دنیا

### Actual Behaviour

all characters shows in reverse direction

سلام دنیا 
ا ی ن د م ا ل س

### Platform
**OS: debian
**Node Version: v8.1.3
**PureImage Version : 0.1.3

**Comment by robertmain** [comment]
Sorry for my ignorance but isn't that desirable? This looks like Arabic text which goes from right to left, no?

**Comment by mohsenxad** [comment]
yes. this is persian but look like arabic too.
right to left(rtl) handwriting

**Comment by robertmain** [comment]
Gotcha. Like I said - I'm somewhat ignorant on the subject, but I'll do my best :)

If you're using `fillText()` as you said, I'm wondering if this is maybe a bug with opentype.js(which we use to do text rendering)

Would you mind going to https://opentype.js.org/ and uploading your font file and seeing if the issue persists on there? Just to see if it's on our end, or a problem with opentype.

**Comment by ameensom** [comment]
Hello
I'm facing the same issue, it's not showing up in opentype.js.org, I've uploaded the font file, and there was no error with how the font is rendered

**Comment by mohsenxad** [comment]
I use "﻿arabic-reshaper" package to get rid of this problem. 
```
pip install arabic-reshaper
```
