### ISSUE TITLE
Exported PNG not transparent

### ISSUE THREAD

**Issue by rinne** [joshmarinacci/node-pureimage#56]
### Expected Behaviour

1. Canvas should by default be transparent and so should in my opinion be the exported bitmap if the export format supports that.

### Actual Behaviour

```
var fs = require('fs');
var PImage = require('pureimage');
var img1 = PImage.make(100,50);
PImage.encodePNGToStream(img1, fs.createWriteStream('out.png')).then(()=> {
    console.log("wrote out the png file to out.png");
}).catch((e)=>{
    console.log("there was an error writing");
});
```

Results an opaque black PNG.

**Comment by elmbrent** [comment]
`var fs = require('fs');
var PImage = require('pureimage');
var img1 = PImage.make(100,50);
var context = img.getContext('2d')
context.clearRect(0, 0, 100,50)
PImage.encodePNGToStream(img1, fs.createWriteStream('out.png')).then(()=> {
    console.log("wrote out the png file to out.png");
}).catch((e)=>{
    console.log("there was an error writing");
});`

**Comment by joshmarinacci** [comment]
You are right. According to the spec a canvas is transparent by default. I've confirmed this experimentally as well.

I've just pushed back a change which makes the bitmap be clear by default. This should automatically work with exported PNGs as well.

Note that the spec also indicates you can create an opaque canvas by passing an option to getContext(). We should support this in the future.


https://html.spec.whatwg.org/multipage/canvas.html#the-canvas-element
