### ISSUE TITLE
Text rendering is slightly pixelated

### ISSUE THREAD

**Issue by ptsimpso** [joshmarinacci/node-pureimage#57]
Is it expected behavior that text rendering is not super sharp? I've tried creating an image in multiple sizes, with multiple font sizes, and with multiple .ttf files from Google Fonts, and the text always appears to be pixelated.

<img width="924" alt="screen shot 2018-01-30 at 1 22 19 pm" src="https://user-images.githubusercontent.com/3860841/35592338-867609a8-05c1-11e8-9733-7f401c542981.png">

Here is my code:
```
    var fnt = PImage.registerFont('RammettoOne-Regular.ttf', 'RammettoOne');
    fnt.load(function () {
        var img = PImage.make(1500, 1500);
        var ctx = img.getContext('2d');
        ctx.fillStyle = 'rgba(0,0,255, 1.0)';
        ctx.fillRect(0, 0, 1000, 1000);
        ctx.fillStyle = '#ffffff';
        ctx.font = "50pt 'RammettoOne'";
        ctx.fillText("My Trunkshow", 50, 200);

        PImage.encodePNGToStream(img, fs.createWriteStream('out.png')).then(() => {
            response.sendFile('out.png', { root: __dirname });
        }).catch((e) => {
            response.send('Error');
        });
    });

**Comment by robertmain** [comment]
I'm having a hard time recreating this - can you tell me a bit more about your OS, node version. etc.?

Also - could you try grabbing the latest version of pureimage off master `npm install git+https://git@github.com/joshmarinacci/node-pureimage.git`

```js
const PImage = require('pureimage');
const fs     = require('fs');

var fnt = PImage.registerFont('./RammettoOne-Regular.ttf', 'RammettoOne');
fnt.load(function () {
    var img = PImage.make(1500, 1500);
    var ctx = img.getContext('2d');

    ctx.fillStyle = 'rgba(0,0,255, 1.0)';
    ctx.fillRect(0, 0, 1000, 1000);
    ctx.fillStyle = '#ffffff';
    ctx.font = "50pt 'RammettoOne'";
    ctx.fillText("My Trunkshow", 50, 200);

    PImage.encodePNGToStream(img, fs.createWriteStream('out.png')).then(() => {
        console.log('Done.')
    }).catch(e => console.error(e));
});
```

Using the code above (which is the same as yours give or take a bit of variable alignment), I was able to generate the following image, which looks perfectly sharp.

I also grabbed a copy of the font from here: https://fonts.google.com/specimen/Rammetto+One?selection.family=Rammetto+One

![out](https://user-images.githubusercontent.com/537684/35604273-819abb42-060f-11e8-9b90-a74c2929e41a.png)

---

The image you provided looks like it's been somehow artificially stretched or resized beyond it's original resolution. Is it possible that this is taking place somewhere else in your application?

**Comment by robertmain** [comment]
Sorry - I just spotted what you meant @ptsimpso - I see the jagged edges round the letters. Let me take a look...

**Comment by robertmain** [comment]
Hmm, kinda looks as though it's not being anti-aliased properly...

**Comment by robertmain** [comment]
Looks like it's something to do with the implementation of `quadraticCurveTo()`. 

I put together a simple example drawing a quadratic curve with pureimage.

```js
const PImage = require('pureimage');
const fs     = require('fs');

const img = PImage.make(200, 200);
const ctx = img.getContext('2d');

//Blue rectangle
ctx.fillStyle = 'rgba(255, 255, 255, 1.0)';
ctx.fillRect(0, 0, img.width, img.height);

//Arc
ctx.beginPath();
ctx.moveTo(50,20);
ctx.quadraticCurveTo(230, 30, 50, 100);
ctx.stroke();
ctx.closePath();

PImage.encodePNGToStream(img, fs.createWriteStream('out.png')).catch(e => console.error(e));

```

This gives me
![image](https://user-images.githubusercontent.com/537684/35660461-16097f6e-06da-11e8-81b1-c68983fd88be.png)



It's quite easy there to see the jaggedy lines in the curve.

Even more so, if we compare this what I get from chrome's implementation of `canvas` , which produces a nice smooth line like so:  
![image](https://user-images.githubusercontent.com/537684/35660478-2bf6c7d2-06da-11e8-89d2-7d5845d8e6b5.png)

**Comment by joshmarinacci** [comment]
Fundamentally PureImage only knows how to draw lines. All of the curves are turned into a sequence of lines. In the quadractic case there is a loop that looks like this:

```
            for(var t=0; t<1; t+=0.1) {
                var pt = calcQuadraticAtT(pts,t);
                lines.push(new Line(curr, pt));
                curr = pt;
            }
```

This chops up the curve into lines going from 0 to 1 at a step of 0.1, meaning ten lines.

Chrome probably uses more lines, but they also probably have an adaptive algorithm that uses different numbers of lines for different curves. Probably derived from this

https://en.wikipedia.org/wiki/De_Casteljau%27s_algorithm

(or they might use something completely different if they do curve rasterization on the GPU)

**Comment by joshmarinacci** [comment]
I've just pushed back a new curve implementation that is adaptive and should appear to be much smoother. Could you test the new code?

**Comment by csmartinsfct** [comment]
@joshmarinacci 

![image](https://github.com/user-attachments/assets/8ee39827-5a5a-4887-8f2c-f8ed8eda59b3)

Any ideas why it looks the way it does? Pixelated, not aligned...

I generated the image above with this code:

```
  const image = PImage.make(200, 44);
  const ctx = image.getContext('2d');
  ctx.fillStyle =
    '#' + ((Math.random() * 0xffffff) << 0).toString(16).padStart(6, '0');
  ctx.fillRect(0, 0, 200, 44);
  ctx.fillStyle = '#000000';
  ctx.font = '25px MyFont';
  ctx.fillText('Hello world!', 20, 30);

  await PImage.encodePNGToStream(
    image,
    fs.createWriteStream(getAssetPath('test.png')),
  );
```

I've loaded the font like so:

```
const font = PImage.registerFont(
  getAssetPath('source-sans-pro-regular.ttf'),
  'MyFont',
);
font.loadSync();
```

Font looks like this on `opentype.js`

<img width="989" alt="Screenshot 2024-11-17 at 4 38 27 PM" src="https://github.com/user-attachments/assets/7193b167-5a4e-4c1c-8647-43b23c27c253">

Thanks!
