### ISSUE TITLE
Please bump up the package version for npm

### ISSUE THREAD

**Issue by jssuttles** [joshmarinacci/node-pureimage#59]
### Expected Behaviour

1. npm install grabs the latest packages

### Actual Behaviour

1. npm install grabs jpeg-js@0.0.4

### Steps To Reproduce

1. npm install

### Platform
**OS: macOS **
**Node Version: 7.7.3 **
**NPM Version: 4.1.2 **
**PureImage Version: 0.1.3 **

### Any Additional Info
npm needs another version bump

**Comment by robertmain** [comment]
Is it `node-pureimage` you're referring to as needing a version bump(it kinda does..) or it's dependencies?

**Comment by jssuttles** [comment]
I don't know how npm module publishing works exactly. But I think the current published version is old.
The packages were updated with this commit: https://github.com/joshmarinacci/node-pureimage/commit/27d97faa505c4c8bb6e9e99fc76919a4a21e7286#diff-b9cfc7f2cdf78a7f4b91a753d10865a2
But the version of this npm module was not updated from 0.1.3 -> 0.1.4 and was not republished to npm with the changes, I think.
I just found that this issue is basically a duplicate of https://github.com/joshmarinacci/node-pureimage/issues/30. 
So here's this: https://docs.npmjs.com/getting-started/publishing-npm-packages

**Comment by jssuttles** [comment]
To test:
Please use npm to install pureimage on a project.
look at the package.json inside the node_modules folder
I believe that you should see that the old packages are referenced instead of the new ones.
Thanks!

**Comment by robertmain** [comment]
Ah, yeah. That makes sense. NPM publishing is done by the package author running `npm publish`.

**Comment by jssuttles** [comment]
So, @joshmarinacci would have to do it, and then I think #30 could be closed as well.

**Comment by robertmain** [comment]
Basically - yes. There have been several bugs fixed since the last version bump that would be nice to roll out to people consuming the lib via `npm` and `yarn` as well...

**Comment by joshmarinacci** [comment]
Done. 0.1.4 is published.
