### ISSUE TITLE
Work in web worker

### ISSUE THREAD

**Issue by volodalexey** [joshmarinacci/node-pureimage#6]
Is ti possible to run this library in web worker?

I am curious, if I can [render all points/constrains in web worker](https://github.com/volodalexey/cloth-web-worker) with the help of your library and just pass the image data to the main thread to draw it in real canvas.

**Comment by joshmarinacci** [comment]
The library doesn't use anything Node specific, so I think it would run in a web worker. I've never tried.  However, it is significantly slower than real canvas, so I'm not sure it would work for your use case. What are you trying to accomplish by using a web worker?

**Comment by volodalexey** [comment]
Inside web worker I will need such functions:
```
    ctx.beginPath();
    ctx.strokeStyle = 'rgb(0,0,255)';
    ctx.moveTo(x1,y1);
    ctx.lineTo(x2, y2);
    ctx.stroke();
```
And as a result:
`canvas.toDataURL();`
or
`ctx.getImageData();`

Looks like your library does not have such functions, does it?

**Comment by joshmarinacci** [comment]
No, my library does not have such functions, but I think it would be easy to add.  The data is stored in an internal bitmap array. It wouldn’t be hard to expose that as the ImageData object that ctx.getImageData() returns. Probably easier than implementing toDataURL();

-j

**Comment by joshmarinacci** [comment]
getImageData has been implemented
