### ISSUE TITLE
Inconsistent Line fill and stray lines

### ISSUE THREAD

**Issue by rthomps7** [joshmarinacci/node-pureimage#62]
### Expected Behaviour

1. Draw a rectangle rounded corners by using a path and fill.

### Actual Behaviour

1. Sometimes there are stray lines.

### Steps To Reproduce

1. Use the code below. It's worth noting this happens even if I draw a simple rectangle, but I figured I may as well share my exact issue.

### Any Relevant Code Snippets

```js
var img = PImage.make(1200, 628),
      ctx = img.getContext('2d'),
      WIDTH = 1200,
      HEIGHT = 628,

ctx.imageSmoothingEnabled = true;

// clear background
ctx.clearRect(0, 0, WIDTH, HEIGHT);

// background
ctx.fillStyle = '#FFFFFF';
ctx.fillRect(0, 0, WIDTH, HEIGHT);

// top color box
ctx.fillStyle = '#142C6E';
ctx.fillRect(0, 0, 338, HEIGHT / 2);

// bottom color box
ctx.fillStyle = "FF0000";
ctx.fillRect(0, HEIGHT / 2, 338, HEIGHT / 2);

// white rectangle box
ctx.fillStyle = '#00FF00';
roundRect(ctx, 44, 239, 250, 150, 8);

    function roundRect(ctx, x, y, width, height, radius) {
      if (typeof radius === 'undefined') {
        radius = 5;
      }
      if (typeof radius === 'number') {
        radius = {tl: radius, tr: radius, br: radius, bl: radius};
      } else {
        var defaultRadius = {tl: 0, tr: 0, br: 0, bl: 0};
        for (var side in defaultRadius) {
          radius[side] = radius[side] || defaultRadius[side];
        }
      }
      ctx.beginPath();
      ctx.moveTo(x + radius.tl, y);
      ctx.lineTo(x + width - radius.tr, y);
      ctx.quadraticCurveTo(x + width, y, x + width, y + radius.tr);
      ctx.lineTo(x + width, y + height - radius.br);
      ctx.quadraticCurveTo(x + width, y + height, x + width - radius.br, y + height);
      ctx.lineTo(x + radius.bl, y + height);
      ctx.quadraticCurveTo(x, y + height, x, y + height - radius.bl);
      ctx.lineTo(x, y + radius.tl);
      ctx.quadraticCurveTo(x, y, x + radius.tl, y);
      ctx.lineTo(x + radius.tl, y);
      ctx.closePath();
      ctx.fill_aa();
    }


```

### Platform
**OS:** OSX
**Node Version:** 8.8.1
**NPM Version:** 5.6.0
**PureImage Version:** 0.1.4 (also, have tried installing from github)

### Any Additional Info

See these images:

Working: 
![working](https://user-images.githubusercontent.com/1281124/37989891-451e14d4-31ca-11e8-8ceb-d55c261485e2.png)

Broken:
![broken](https://user-images.githubusercontent.com/1281124/37989894-4804e006-31ca-11e8-92bc-e975fb6442d0.png)

**Comment by rthomps7** [comment]
More information: It appears when I load up my server, the issue happens only the first time I create an image. If I keep creating images, it's fine on images moving forward.

**Comment by joshmarinacci** [comment]
Weird. That implies there is some internal state that gets changed the first time you draw something.  If you draw two round rects in the same image, does only the first one have that problem?

**Comment by rthomps7** [comment]
(I provided some updated code at the bottom for testing.)

The behavior is slightly different for me today. However, that's likely because I now have a stripped down script running this instead of using it inside of a bigger application. Similar issues are still present:

When I run it the first time, it looks like [this](https://user-images.githubusercontent.com/1281124/38118260-2bcf9ab4-337f-11e8-831c-c8c6f35ecac3.png).

When I run it twice on one script, it looks like [this](https://user-images.githubusercontent.com/1281124/38118288-653ba13a-337f-11e8-945c-15955e705271.png).

Drawing two boxes, it looks like [this](https://user-images.githubusercontent.com/1281124/38118311-7f0307a2-337f-11e8-9478-75de56690034.png) (appears to be working on the second box).

Not to conflate issues here, and I don't have time for a formal issue report, I had to move on to the regular node-canvas library because I had issues loading png images that had transparency on top of my canvas. I think I realized you were overwriting all pixels with the new image, but if it's alpha was zero it would override the current pixel and set it to black. I fixed that locally. It was close to working, but there were black spots around text in a transparent image. I didn't have time to take it further. Thought I'd point it out.

```js
var PImage= require('pureimage'),
    fs = require('fs');

create();

var img = create();

PImage.encodePNGToStream(img, fs.createWriteStream('out.png')).then(() => {
  console.log("wrote out the png file to out.png");
}).catch((e)=>{
  console.log("there was an error writing");
  console.log(e);
});

function create() {
  var img = PImage.make(1200, 628),
      ctx = img.getContext('2d'),
      WIDTH = 1200,
      HEIGHT = 628;

  ctx.imageSmoothingEnabled = true;

  // clear background
  ctx.clearRect(0, 0, WIDTH, HEIGHT);

  // background
  ctx.fillStyle = '#FFFFFF';
  ctx.fillRect(0, 0, WIDTH, HEIGHT);

  // top color box
  ctx.fillStyle = '#142C6E';
  ctx.fillRect(0, 0, 338, HEIGHT / 2);

  // bottom color box
  ctx.fillStyle = "#FF0000";
  ctx.fillRect(0, HEIGHT / 2, 338, HEIGHT / 2);

  // Green rectangle box
  ctx.fillStyle = '#00FF00';
  roundRect(ctx, 44, 239, 250, 150, 8);

  return img;

  function roundRect(ctx, x, y, width, height, radius) {
    if (typeof radius === 'undefined') {
      radius = 5;
    }
    if (typeof radius === 'number') {
      radius = {tl: radius, tr: radius, br: radius, bl: radius};
    } else {
      var defaultRadius = {tl: 0, tr: 0, br: 0, bl: 0};
      for (var side in defaultRadius) {
        radius[side] = radius[side] || defaultRadius[side];
      }
    }
    ctx.beginPath();
    ctx.moveTo(x + radius.tl, y);
    ctx.lineTo(x + width - radius.tr, y);
    ctx.quadraticCurveTo(x + width, y, x + width, y + radius.tr);
    ctx.lineTo(x + width, y + height - radius.br);
    ctx.quadraticCurveTo(x + width, y + height, x + width - radius.br, y + height);
    ctx.lineTo(x + radius.bl, y + height);
    ctx.quadraticCurveTo(x, y + height, x, y + height - radius.bl);
    ctx.lineTo(x, y + radius.tl);
    ctx.quadraticCurveTo(x, y, x + radius.tl, y);
    ctx.lineTo(x + radius.tl, y);
    ctx.closePath();
    ctx.fill_aa();
  }
}

```

**Comment by joshmarinacci** [comment]
Hmm. This is very strange. I'm running your code above and it doesn't have the glitch. I'm also on mac, though with a newer version of Node. And you said it happens from both npm and git?

**Comment by rthomps7** [comment]
@joshmarinacci 

Well, that code I pasted works, since it calls `create` twice in the same script.

Comment out the first `create` and I think you'll see the issue. If not, then I will be very confused.

**Comment by joshmarinacci** [comment]
I'm sorry it took so long to get back to this. I've created a new unit test based on your code. It does not show the rendering artifacts anymore. I have rewriting a bunch of path and stroke code since your original bug, so hopefully those fixed your issues. Note, you can't use `ctx.fill_aa()` directly. That is used internally and takes an array of Line objects. You should use the `ctx.fill()` method instead. It will still be antialiased thanks to the `imageSmoothingEnabled` property.
