### ISSUE TITLE
Synchronous version of encodePNGToStream?

### ISSUE THREAD

**Issue by CoenraadS** [joshmarinacci/node-pureimage#63]
I was wondering if its possible to add a synchronous api? Great project btw

**Comment by robertmain** [comment]
Out of curiosity, why would you want a synchronous API?

**Comment by CoenraadS** [comment]
I was trying to use it in a VSCode extension, where I listen to a non-async event

**Comment by joshmarinacci** [comment]
I don't think it's possible. You have to use the Promise.  Underneath the PNG encoder uses streams so we have to wait for a 'finish' event. There is no synchronous API.
