### ISSUE TITLE
Extraneous "console.log" should be removed

### ISSUE THREAD

**Issue by justmike** [joshmarinacci/node-pureimage#66]
Hi-
It looks like you left behind a `console.log` line:

https://github.com/joshmarinacci/node-pureimage/blob/903b8b21c6157b3c4e9d50b356d7b3ac68c4bd58/src/text.js#L94

Thanks!

**Comment by robertmain** [comment]
I wonder if we should configure eslint or something for this

**Comment by joshmarinacci** [comment]
sorry about that. fixed now.
