### ISSUE TITLE
docs just JSON?

### ISSUE THREAD

**Issue by opyate** [joshmarinacci/node-pureimage#67]
### Expected Behaviour

1. readable docs

### Actual Behaviour

1. docs just JSON (http://joshmarinacci.github.io/node-pureimage)

### Steps To Reproduce

1. click http://joshmarinacci.github.io/node-pureimage

**Comment by opyate** [comment]
Workaround: build local docs.

**Comment by robertmain** [comment]
WHOAH! that's not right!

I'm busy most of today but let me look into that this evening or tomorrow

**Comment by robertmain** [comment]
@joshmarinacci can you sign in to travis and try re-running the build? I think that might resolve this?

**Comment by joshmarinacci** [comment]
I just restarted the build. Let's see if that fixes it.

**Comment by robertmain** [comment]
Weird. I wonder if it's a bug with esdoc...

**Comment by Farkal** [comment]
Any update on this ?

**Comment by rmainseas** [comment]
This looks to be fixed now, @Farkal

**Comment by Farkal** [comment]
Yes thanks i think you can close this issue.

**Comment by joshmarinacci** [comment]
Thanks
