### ISSUE TITLE
arc() dont work as expected

### ISSUE THREAD

**Issue by jmgk77** [joshmarinacci/node-pureimage#76]
### Expected Behaviour

1. using canvas.js or in browser: ctx.arc(100,100,50,1.7*Math.PI,0.7*Math.PI); 

![canvas](https://user-images.githubusercontent.com/46632344/53852665-9397e280-3fa1-11e9-9099-313e81e338b3.png)

### Actual Behaviour

1. using pureimage: ctx.arc(100,100,50,1.7*Math.PI,0.7*Math.PI);

![pureimage](https://user-images.githubusercontent.com/46632344/53852666-9397e280-3fa1-11e9-87e0-ab58aabd5a76.png)
### Any Relevant Code Snippets

canvas:
```js
{	const { createCanvas } = require('canvas');
	const canvas = createCanvas(200, 200);
	const ctx = canvas.getContext('2d');
	ctx.beginPath();
	ctx.fillStyle = "white";
	ctx.fillRect(0, 0, 200, 200);
	ctx.beginPath();
	ctx.arc(100,100,50,1.7*Math.PI,0.7*Math.PI);
	ctx.stroke();	
	const fs = require('fs');
	const out = fs.createWriteStream('canvas.png');
	const stream = canvas.createPNGStream();
	stream.pipe(out);
}
```
pureimage
```js
{	var PImage = require('pureimage');
	var img = PImage.make(200, 200);
	var ctx = img.getContext('2d');
	ctx.beginPath();
	ctx.fillStyle = "white";
	ctx.fillRect(0, 0, 200, 200);
	ctx.beginPath();
	ctx.arc(100,100,50,1.7*Math.PI,0.7*Math.PI);
	ctx.stroke();	
	var fs = require('fs');
	PImage.encodePNGToStream(img, fs.createWriteStream('pureimage.png'));
}
```

### Platform
**OS:**ubuntu 16.04
**Node Version:**v8.15.1
**NPM Version:**6.4.1
**PureImage Version:**pureimage@0.1.6

**Comment by joshmarinacci** [comment]
Good catch. I looks like the problem happens when the arc goes backwards.  going from 0->pi draws a correct half circle. Drawing from pi->0 draws a straight line.

**Comment by joshmarinacci** [comment]
at least partially fixed by https://github.com/joshmarinacci/node-pureimage/commit/fe722f065d4365b3b3d0ae45ad982d8be9c28b87

**Comment by joshmarinacci** [comment]
I think this will fix it.

**Comment by joshmarinacci** [comment]
Could you test again?

**Comment by jmgk77** [comment]
Fixed! Good work

Thanks
