### ISSUE TITLE
looks like has some code need to fix

### ISSUE THREAD

**Issue by bluelovers** [joshmarinacci/node-pureimage#78]
> text

![image](https://user-images.githubusercontent.com/167966/60389669-9e4e2880-9af8-11e9-9d49-de3cf0fce614.png)

> context

![image](https://user-images.githubusercontent.com/167966/60389674-ae660800-9af8-11e9-8b32-2041f47132cb.png)

![image](https://user-images.githubusercontent.com/167966/60389843-d60a9f80-9afb-11e9-8974-20822be1157e.png)

---

unsafe type handle

![image](https://user-images.githubusercontent.com/167966/60389858-2aae1a80-9afc-11e9-8007-71295fc9ecce.png)

![image](https://user-images.githubusercontent.com/167966/60389860-300b6500-9afc-11e9-9891-6a45d8d7996a.png)

> transform

![image](https://user-images.githubusercontent.com/167966/60389677-c3429b80-9af8-11e9-99ee-8c09562763b6.png)

================

and hope can rewrite to typescript
https://github.com/bluelovers/node-pureimage/tree/master/src

for better type check and easy use api

**Comment by joshmarinacci** [comment]
thanks.

**Comment by robertmain** [comment]
Seconded regarding TypeScript. I've had this thought for a long time. Happy to help if there's interest in this...

**Comment by joshmarinacci** [comment]
I'm interested in using Typescript but I don't have the time or knowledge to implement it. However, if someone would like to take this on I'm happy to support it.

**Comment by bluelovers** [comment]
https://github.com/bluelovers/node-pureimage/tree/master/src

**Comment by joshmarinacci** [comment]
Oh wow!  Yes, please create a new issue for Typescript and submit a pull request.
