### ISSUE TITLE
decodePNGFromStream() causes PNGs to lose their transparency.

### ISSUE THREAD

**Issue by soulos45** [joshmarinacci/node-pureimage#82]
Using `PImage.decodePNGFromStream` causes PNG files with transparency to render without any. 

Tried `new PNG({ colorType: 6, inputHasAlpha: true })` and on the `metadata` event, everything seems fine.

I guess the bug is somewhere inside the Bitmap class.

Any help would be really appreciated,
Thank you in advance fellow developers :)

**Comment by jarrodwatts** [comment]
What was your solution for this issue @soulos45?

**Comment by joshmarinacci** [comment]
Is this bug happening to you? Could you send me a test case to reproduce it? I haven't been able to.

**Comment by solace** [comment]
Hi! Thanks for this package.

The png renders with a black background using this code fragment. I've tried running the buffer through `sharp` and changing the background to `rgba(255, 255, 255, 0)` before passing it into `Readable.from` and it renders with a white background instead. So it looks like somewhere along the way it's losing the alpha.

```
const response = await fetch(url);
const buffer = Buffer.from(await response.arrayBuffer());
const stream = Readable.from(buffer);
const img = await PureImage.decodePNGFromStream(stream);
ctx.drawImage(img, x, y, w, h);
```

I'll see if I can sort out a demo at the weekend.

**Comment by solace** [comment]
Link to repro: https://codesandbox.io/s/node-js-test-forked-kxp643

Nav to `/image` in the sandbox browser to trigger download of the generated image which I have also attached.

Note that the react icon should be transparent, not black. This demo also demonstrates a clipping issue I am experiencing which I will detail in a new ticket.

![test (6)](https://user-images.githubusercontent.com/374583/197330457-1b993aca-5374-4ae2-a25c-7c560a675bd1.jpg)
