### ISSUE TITLE
renderGlyphToBitmap is not defined

### ISSUE THREAD

**Issue by jssuttles** [joshmarinacci/node-pureimage#85]
https://github.com/joshmarinacci/node-pureimage/blob/4860360ade650e5d6319b3da85061af916a39e09/src/text.js#L100
Seems like after the refactor, this line was left behind.

**Comment by joshmarinacci** [comment]
Hmm. Yeah, it looks like USE_FONT_GLYPH_CACHING is completely gone.

**Comment by joshmarinacci** [comment]
I just nuked the reference to caching, since it clearly doesn't work anyway.
