### ISSUE TITLE
incorrect return type for registerFont

### ISSUE THREAD

**Issue by SheetJSDev** [joshmarinacci/node-pureimage#86]
### Expected Behaviour

JSDoc comment asserts a return type that isn't void

### Actual Behaviour

JSDoc comment claims return type is void

### Steps To Reproduce

Using TypeScript:

```typescript
import * as PImage from "pureimage";
PImage.registerFont("./Font.ttf", "Font", 400, "normal", "normal").load(() => {})
```

`registerFont` returns the font object which has a `load` method, so that should pass typescript checker.  However, tsc looks at the JSDoc and believes it returns void

**Comment by joshmarinacci** [comment]
See if this fixes it.

**Comment by SheetJSDev** [comment]
That worked tyvm
