### ISSUE TITLE
lineWidth

### ISSUE THREAD

**Issue by brainlessboy** [joshmarinacci/node-pureimage#98]
### Expected Behaviour

1. lineWidth = 5; // would stroke a rectangle with 5px width

### Actual Behaviour

1. always strokes 1 or 2 pixel

### Steps To Reproduce

ctx.strokeStyle = 'rgba(0,0,0, 1)';
ctx.lineWidth = 10;      
ctx.strokeRect(10, 10, 100, 100);

executed on OSX and Node v11.0.0

**Comment by CapsE** [comment]
I can reproduce that behaviour on Windows 10

**Comment by kfaubel** [comment]
I was wondering if there were any updates on this.  I am tired of dealing with canvas and the native dependencies and have ported a weather graphing app to pureimage but the graph lines are too thin.
Original (with canvas): https://imgur.com/gallery/r5XPftO
New (with pureimage): https://imgur.com/a/GwkIlwh 

Are there any workarounds? Thanks.

**Comment by joshmarinacci** [comment]
I just added a unit test in the linewidth branch to test this. It looks like lineWidth is used now. When I create a thick square I can see that it's actually using thicker lines. However, when I create a thick curve there are weird notches all over the curve, though again it is thicker.

Looking at the code it appears that we draw each line independently by stroking it wide with AA respecting code. However, the end of each line is pointed. There is no join between each line because they are independent. This is what is creating the notches.  Curves are drawn by converting them to a series of lines, so they get lots of notches.

I think the solution is to rewrite the line drawing code. Instead of drawing each line independently the entire sequence of lines should be turned into a new wider polygon with proper joins, then fill the new polygon.

**Comment by kfaubel** [comment]
Thanks for the reply.  As you could see I did get thicker lines but, yeah, the plot has notches.  I did see references to lineJoin and I tried a few things but it did not make a difference.  It sounds like you know what the real issue is.

Should lineWidth be working with strokeRect.  It did not seem to be for me.  I replace that call with drawing the sides myself with stroke and that worked.

I really appreciate the project.  Dealing with canvas across platforms and versions takes the fun out of things.

**Comment by joshmarinacci** [comment]
I've created a branch called 'linewidth'.  This uses an updated algorithm that calculates a new polygon based on the original line and the specified linewidth.  I'm able to get images that look like this now:

![thick_stroke_square](https://user-images.githubusercontent.com/276938/123828832-e367e980-d8cf-11eb-8ae2-5a3624c98d4e.png)
![thick_stroke_curve](https://user-images.githubusercontent.com/276938/123828848-e7940700-d8cf-11eb-816b-823d2b4ffbb2.png)


It's not perfect but it is a lot better now.

Can you try out this branch with your code and see how it looks?

**Comment by kfaubel** [comment]
I am not sure that I did this correctly.  I did: 
$  git clone --branch linewidth https://github.com/joshmarinacci/node-pureimage.git
$ cd node-pureimage
$ npm install
$ npm run build

I then copied dist/pureimage-umd.cjs to the node_modules/pureimage/dist/ directory in my project.  This replaced the file of the same name.

I re-ran my project to generate a new image and did not get what I expected.

There is probably a better way to pull in the pureimage dependency but I am not sure what it is.

The resulting image is recognizable but the lines are all not right.  See: https://imgur.com/a/AqKmZVq
The image build minutes earlier with the 0.3.2 version is: https://imgur.com/a/NYsZgyS 

To run my app I did:
$ git clone https://github.com/kfaubel/weather-builder.git
$ cd weather-builder
$ npm install
$ npm start

Thanks

**Comment by joshmarinacci** [comment]
Could you post a small app or bit of code to recreate your image (or a subset of it)? Then I could test against that code to make sure it works.

**Comment by kfaubel** [comment]
I included the steps to clone and build my test app at the bottom of my
post.  Copied here:
To run my app I did:
$ git clone https://github.com/kfaubel/weather-builder.git
$ cd weather-builder
$ npm install
$ npm start

Ken

**Comment by joshmarinacci** [comment]
I can recreate the bugs now. I'll work on it this weekend.

**Comment by joshmarinacci** [comment]
I just pushed back some changes that improve it. I found two issues:

1) the code expands by the full lineWidth in each direction, giving you double wide lines. Now it uses half the lineWidth, so the complete line is the actual lineWidth.
2) it was generating infinite numbers when two adjacent paths in a point are the same. The spec doesn't say what should happen in this case (it's technically an invalid path), but if I just skip the dupes it seems to work. Here's what it looks like now.

I still don't know what the two large blue columns are.Is that supposed to be rain?

![foo](https://user-images.githubusercontent.com/276938/125126859-92ff4180-e0b0-11eb-988e-e05a0779d8dc.png)

**Comment by kfaubel** [comment]
Thanks for your work on this.  The plot lines look great.

The background shading is in layers.
- The grey is cloud cover from 0-100%.  I draw it first
- The dark blue is the probability of rain 0-100%. I draw this second.
- The lighter blue is the QDF (amount of precipitation).  I draw that third.
You can see at noon on Sunday there will be about 60% cloud cover, a 10% chance of rain but no predicted accumulation.  When there is lots of accumulation predicted, the chance of rain and cloud cover are nit very important.

The light blue does not look right.  The image below is 24 hours after yours above so the forecast has changed, but the light blue should be down around 10 and not up at 100.  All of the other data looks correct.
![image](https://user-images.githubusercontent.com/50021398/125172633-c1e8e680-e188-11eb-8015-9f74eb3353c9.jpg)

**Comment by kfaubel** [comment]
Sorry for the delay.  I meant to get you a sample program that showed the problem.  I can't get it to fail again and I tried several programs that do similar things.  I did write a simple test program but it did not show the issue I saw back then.  The tall blue pillars used beginPath(), moveTo(), lineTo...fill() to do the drawing.  I assume I did something wrong.

I noticed that a line I had in another project had a requested width of 20, but when I run with your updated library, it shows much wider than before.  I zoomed in and the new library is correct.  The old library seemed to drawing it at about 10 pixels wide.  I don't know if that fits matches your comment above but it looks correct.

I do see these lines being printed in the console.  The code:
```
ctx.strokeStyle = "#FFFFFF";
ctx.lineWidth = 3;
ctx.beginPath();
ctx.arc(500, 500, 200, 0, 2 * Math.PI);
ctx.stroke();
```
Causes:
can't project the same paths 1 [ 'l', Point { x: 700, y: 500 } ] Point { x: 700, y: 500 } Point { x: 700, y: 500 }

Output looks fine.

**Comment by joshmarinacci** [comment]
Yeah, it turns out I'd been doing the line width wrong the whole time. 😆 
The console log output is a warning that you can ignore for now.  It won't hurt anything.
It seems stable enough now so I'll merge in the changes and push out a release.

**Comment by kfaubel** [comment]
Should I see a dist folder in 3.0.4?

**Comment by joshmarinacci** [comment]
Oops. My mistake. I rebuilt and pushed out 0.3.5
